// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "test.h"
#include <FL/Fl_Native_File_Chooser.H>
static Fl_Native_File_Chooser *chooser; 
static Fl_Text_Buffer *textbuf; 
static const char *file; 

void open_file() {
  textbuf->loadfile(file);
  
  const char* tmp = "opened ";
  char buffer[256];
  strncpy(buffer, tmp, sizeof(buffer));
  strncat(buffer, file, sizeof(buffer));
  
  main_window->label(buffer);
}

void save_file() {
  textbuf->savefile(file);
    
  const char* tmp = "saved ";
  char buffer[256];
  strncpy(buffer, tmp, sizeof(buffer));
  strncat(buffer, file, sizeof(buffer));
  
  main_window->label(buffer);
}

void action_new() {
  file ="/tmp/untitled";
  textbuf->select(0, textbuf->length());
  textbuf->remove_selection();
  save_file();
  open_file();
}

void action_open() {
  chooser = new Fl_Native_File_Chooser();
  chooser->type(Fl_Native_File_Chooser::BROWSE_FILE);
  chooser->directory(file);
  if ( chooser->show() ) return;
  file = chooser->filename();
  open_file();
}

void action_save() {
  if (file != NULL) {
    save_file();
  }
}

void action_save_as() {
  chooser = new Fl_Native_File_Chooser();
  chooser->type(Fl_Native_File_Chooser::BROWSE_SAVE_FILE);
  chooser->directory(file);
  chooser->preset_file(file);
  if ( chooser->show() ) return;
  file = chooser->filename();
  save_file();
}

Fl_Double_Window *about_window=(Fl_Double_Window *)0;

Fl_Double_Window* action_about() {
  { about_window = new Fl_Double_Window(335, 290, "About Dialog");
    about_window->color(FL_LIGHT1);
    { Fl_Box* o = new Fl_Box(0, 9, 335, 187, "Emendo FLTK Experimental\n\n0.0.1\nSimple text editor\nCopyright \302\251 alp\
haOS");
      o->labelsize(20);
    } // Fl_Box* o
    { new Fl_Box(0, 204, 335, 81, "This program comes with ABSOLUTELY \nNO WARRANTY. See the GNU General Public \
\nLicense, version 3 or later for details.");
    } // Fl_Box* o
    about_window->set_modal();
    about_window->end();
  } // Fl_Double_Window* about_window
  about_window->show();
  return about_window;
}

void action_about_hide() {
  about_window->hide();
}

Fl_Double_Window *main_window=(Fl_Double_Window *)0;

Fl_Text_Editor *editor=(Fl_Text_Editor *)0;

int main(int argc, char **argv) {
  { main_window = new Fl_Double_Window(755, 575, "Emendo FLTK Experimental");
    main_window->color(FL_LIGHT1);
    { editor = new Fl_Text_Editor(0, 40, 755, 535);
      editor->selection_color((Fl_Color)220);
      editor->labelfont(4);
      editor->labelsize(17);
      editor->textfont(4);
      editor->textsize(17);
      Fl_Group::current()->resizable(editor);
    } // Fl_Text_Editor* editor
    { Fl_Group* o = new Fl_Group(0, 0, 755, 40);
      o->selection_color((Fl_Color)93);
      o->labelcolor(FL_GRAY0);
      { Fl_Button* o = new Fl_Button(5, 5, 75, 30, "New");
        o->color(FL_LIGHT1);
        o->selection_color((Fl_Color)53);
        o->callback((Fl_Callback*)action_new);
        o->align(Fl_Align(256));
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(85, 5, 75, 30, "Open");
        o->color(FL_LIGHT1);
        o->selection_color((Fl_Color)53);
        o->callback((Fl_Callback*)action_open);
        o->align(Fl_Align(256));
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(165, 5, 75, 30, "Save");
        o->color(FL_LIGHT1);
        o->selection_color((Fl_Color)53);
        o->callback((Fl_Callback*)action_save);
        o->align(Fl_Align(256));
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(245, 5, 75, 30, "Save As");
        o->color(FL_LIGHT1);
        o->selection_color((Fl_Color)53);
        o->callback((Fl_Callback*)action_save_as);
        o->align(Fl_Align(256));
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(675, 5, 75, 30, "About");
        o->color(FL_LIGHT1);
        o->selection_color((Fl_Color)53);
        o->callback((Fl_Callback*)action_about);
        o->align(Fl_Align(256));
      } // Fl_Button* o
      o->end();
    } // Fl_Group* o
    main_window->end();
  } // Fl_Double_Window* main_window
  textbuf = new Fl_Text_Buffer();
  editor->buffer(textbuf);
  main_window->show(argc, argv);
  return Fl::run();
}
