// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef test_h
#define test_h
#include <FL/Fl.H>
void open_file();
void save_file();
void action_new();
void action_open();
void action_save();
void action_save_as();
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *about_window;
#include <FL/Fl_Box.H>
Fl_Double_Window* action_about();
void action_about_hide();
extern Fl_Double_Window *main_window;
#include <FL/Fl_Text_Editor.H>
extern Fl_Text_Editor *editor;
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
#endif
