// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef test_h
#define test_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *window;
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
extern Fl_Button *button11;
extern Fl_Button *button12;
extern Fl_Button *button13;
extern Fl_Button *button14;
extern Fl_Button *button15;
extern Fl_Button *button21;
extern Fl_Button *button22;
extern Fl_Button *button23;
extern Fl_Button *button24;
extern Fl_Button *button25;
extern Fl_Button *button31;
extern Fl_Button *button32;
extern Fl_Button *button33;
extern Fl_Button *button34;
extern Fl_Button *button35;
extern Fl_Menu_Item menu_[];
#endif
