// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "test.h"

Fl_Double_Window *window=(Fl_Double_Window *)0;

Fl_Menu_Item menu_[] = {
 {"File", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Quit", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Help", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Help", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Button *button11=(Fl_Button *)0;

Fl_Button *button12=(Fl_Button *)0;

Fl_Button *button13=(Fl_Button *)0;

Fl_Button *button14=(Fl_Button *)0;

Fl_Button *button15=(Fl_Button *)0;

Fl_Button *button21=(Fl_Button *)0;

Fl_Button *button22=(Fl_Button *)0;

Fl_Button *button23=(Fl_Button *)0;

Fl_Button *button24=(Fl_Button *)0;

Fl_Button *button25=(Fl_Button *)0;

Fl_Button *button31=(Fl_Button *)0;

Fl_Button *button32=(Fl_Button *)0;

Fl_Button *button33=(Fl_Button *)0;

Fl_Button *button34=(Fl_Button *)0;

Fl_Button *button35=(Fl_Button *)0;

int main(int argc, char **argv) {
  { window = new Fl_Double_Window(545, 405, "Control Center");
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(25, 25, 490, 30);
      o->color((Fl_Color)55);
      o->selection_color((Fl_Color)70);
      o->labelsize(18);
      o->menu(menu_);
    } // Fl_Menu_Bar* o
    { Fl_Group* o = new Fl_Group(25, 65, 490, 310);
      { button11 = new Fl_Button(25, 65, 90, 90, "button");
        button11->color(FL_DARK2);
        button11->selection_color((Fl_Color)28);
      } // Fl_Button* button11
      { button12 = new Fl_Button(125, 65, 90, 90, "button");
        button12->color(FL_DARK2);
        button12->selection_color((Fl_Color)28);
      } // Fl_Button* button12
      { button13 = new Fl_Button(225, 65, 90, 90, "button");
        button13->color(FL_DARK2);
        button13->selection_color((Fl_Color)28);
      } // Fl_Button* button13
      { button14 = new Fl_Button(325, 65, 90, 90, "button");
        button14->color(FL_DARK2);
        button14->selection_color((Fl_Color)28);
      } // Fl_Button* button14
      { button15 = new Fl_Button(425, 65, 90, 90, "button");
        button15->color(FL_DARK2);
        button15->selection_color((Fl_Color)28);
      } // Fl_Button* button15
      { button21 = new Fl_Button(25, 165, 90, 90, "button");
        button21->color(FL_DARK2);
        button21->selection_color((Fl_Color)28);
      } // Fl_Button* button21
      { button22 = new Fl_Button(125, 165, 90, 90, "button");
        button22->color(FL_DARK2);
        button22->selection_color((Fl_Color)28);
      } // Fl_Button* button22
      { button23 = new Fl_Button(225, 165, 90, 90, "button");
        button23->color(FL_DARK2);
        button23->selection_color((Fl_Color)28);
      } // Fl_Button* button23
      { button24 = new Fl_Button(325, 165, 90, 90, "button");
        button24->color(FL_DARK2);
        button24->selection_color((Fl_Color)28);
      } // Fl_Button* button24
      { button25 = new Fl_Button(425, 165, 90, 90, "button");
        button25->color(FL_DARK2);
        button25->selection_color((Fl_Color)28);
      } // Fl_Button* button25
      { button31 = new Fl_Button(25, 265, 90, 90, "button");
        button31->color(FL_DARK2);
        button31->selection_color((Fl_Color)28);
      } // Fl_Button* button31
      { button32 = new Fl_Button(125, 265, 90, 90, "button");
        button32->color(FL_DARK2);
        button32->selection_color((Fl_Color)28);
      } // Fl_Button* button32
      { button33 = new Fl_Button(225, 265, 90, 90, "button");
        button33->color(FL_DARK2);
        button33->selection_color((Fl_Color)28);
      } // Fl_Button* button33
      { button34 = new Fl_Button(325, 265, 90, 90, "button");
        button34->color(FL_DARK2);
        button34->selection_color((Fl_Color)28);
      } // Fl_Button* button34
      { button35 = new Fl_Button(425, 265, 90, 90, "button");
        button35->color(FL_DARK2);
        button35->selection_color((Fl_Color)28);
      } // Fl_Button* button35
      o->end();
    } // Fl_Group* o
    window->end();
  } // Fl_Double_Window* window
  window->show(argc, argv);
  return Fl::run();
}
