// generated by Fast Light User Interface Designer (fluid) version 1.0303
#include <cstdlib>
#include "test.h"

void action_quit(Fl_Widget*, void*) {
  exit(0);
}

Fl_Menu_Item menu_[] = {
 {"File", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Quit", 0,  (Fl_Callback*)action_quit, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

int main(int argc, char **argv) {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(405, 355);
    w = o;
    o->color((Fl_Color)64);
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 0, 405, 20);
      o->color((Fl_Color)48);
      o->selection_color((Fl_Color)64);
      o->menu(menu_);
    } // Fl_Menu_Bar* o
    { Fl_Box* o = new Fl_Box(85, 29, 235, 61, "Experimental");
      o->labelsize(37);
      o->labelcolor((Fl_Color)48);
    } // Fl_Box* o
    { Fl_Box* o = new Fl_Box(5, 98, 395, 252, "FLTK (pronounced \"fulltick\") \nis a  cross-platform C++ \n GUI toolkit for \
UNIX\302\256/Linux\302\256 (X11), \nMicrosoft\302\256 Windows\302\256, \nand M\
acOS\302\256 X. FLTK provides \nmodern GUI functionality \nwithout the bloat a\
nd \nsupports 3D graphics \nvia OpenGL\302\256 and its built-in \nGLUT emulati\
on.");
      o->labelsize(19);
      o->labelcolor((Fl_Color)135);
    } // Fl_Box* o
    o->end();
    o->resizable(o);
  } // Fl_Double_Window* o
  w->show(argc, argv);
  return Fl::run();
}
