// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "main.h"
#include <unistd.h>
#include <string>
#include <iostream>
#include <cstdio>
#include <FL/Fl_PNG_Image.H>

Fl_Double_Window *win=(Fl_Double_Window *)0;

Fl_File_Browser *b1=(Fl_File_Browser *)0;

Fl_File_Browser *b2=(Fl_File_Browser *)0;

Fl_Input *i1=(Fl_Input *)0;

Fl_Input *i2=(Fl_Input *)0;

Fl_Menu_Item menu_[] = {
 {"File", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Exit", 0,  (Fl_Callback*)action_exit, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Tools", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Open in Terminal", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Help", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"About", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

int main(int argc, char **argv) {
  { win = new Fl_Double_Window(775, 610, "FLTK Commander");
    { b1 = new Fl_File_Browser(5, 70, 380, 505);
      b1->selection_color(FL_DARK_RED);
      b1->labelfont(5);
      b1->labelsize(20);
      b1->labelcolor(FL_GRAY0);
      b1->textfont(5);
      b1->textsize(15);
      b1->callback((Fl_Callback*)b1_clicked);
      b1->type(FL_MULTI_BROWSER);
    } // Fl_File_Browser* b1
    { b2 = new Fl_File_Browser(390, 70, 380, 505);
      b2->selection_color(FL_DARK_RED);
      b2->labelfont(5);
      b2->labelsize(20);
      b2->labelcolor(FL_GRAY0);
      b2->textfont(5);
      b2->textsize(15);
      b2->callback((Fl_Callback*)b2_clicked);
      b2->type(FL_MULTI_BROWSER);
    } // Fl_File_Browser* b2
    { i1 = new Fl_Input(5, 39, 380, 25);
      i1->selection_color((Fl_Color)219);
      i1->labelcolor(FL_GRAY0);
      i1->textfont(5);
      i1->textsize(15);
      i1->callback((Fl_Callback*)i1_changed);
      i1->when(FL_WHEN_ENTER_KEY);
    } // Fl_Input* i1
    { i2 = new Fl_Input(390, 40, 380, 25);
      i2->selection_color((Fl_Color)219);
      i2->labelcolor(FL_GRAY0);
      i2->textfont(5);
      i2->textsize(15);
      i2->callback((Fl_Callback*)i2_changed);
      i2->when(FL_WHEN_ENTER_KEY);
    } // Fl_Input* i2
    { Fl_Group* o = new Fl_Group(5, 575, 790, 35);
      { Fl_Button* o = new Fl_Button(5, 580, 105, 25, "F3 View");
        o->shortcut(0xffc0);
        o->color(FL_LIGHT2);
        o->callback((Fl_Callback*)action_view);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(115, 580, 105, 25, "F4 Edit");
        o->shortcut(0xffc1);
        o->color(FL_LIGHT2);
        o->callback((Fl_Callback*)action_edit);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(225, 580, 105, 25, "F5 Copy");
        o->shortcut(0xffc2);
        o->color(FL_LIGHT2);
        o->callback((Fl_Callback*)action_copy);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(335, 580, 105, 25, "F6 Move");
        o->shortcut(0xffc3);
        o->color(FL_LIGHT2);
        o->callback((Fl_Callback*)action_move);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(445, 580, 105, 25, "F7 New Folder");
        o->shortcut(0xffc4);
        o->color(FL_LIGHT2);
        o->callback((Fl_Callback*)action_new_folder);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(555, 580, 105, 25, "F8 Delete");
        o->shortcut(0xffc5);
        o->color(FL_LIGHT2);
        o->callback((Fl_Callback*)action_delete);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(665, 580, 105, 25, "Alt+F4 Exit");
        o->color(FL_LIGHT2);
        o->callback((Fl_Callback*)action_exit);
      } // Fl_Button* o
      o->end();
    } // Fl_Group* o
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(5, 7, 765, 25);
      o->menu(menu_);
    } // Fl_Menu_Bar* o
    win->size_range(700, 410);
    win->end();
    win->resizable(win);
  } // Fl_Double_Window* win
  b1->load("/");
  b2->load(".");
  i1->value("/");
  char *buf;
  buf=(char *)malloc(100*sizeof(char));
  getcwd(buf, 100);
  i2->value(buf);
  const char *name = "folder.png"; 
  Fl_PNG_Image *img = new Fl_PNG_Image(name);
  win->icon(img);
  win->show(argc, argv);
  return Fl::run();
}

void open_folder(const char *f, Fl_File_Browser *b, Fl_Input *i) {
  int ret_val = chdir(f);
  if(0 == ret_val)
  {
      char *buf;
      buf=(char *)malloc(100*sizeof(char));
      getcwd(buf, 100);
      b->load(buf);
      i->value(buf);
  }
}

void b1_clicked() {
  b2->deselect();
  if( Fl::event_button() == FL_RIGHT_MOUSE )
      return;
  int index = b1->value();
  if (index == 0) return;
  const char *file = b1->text(index);
  const char *dir = i1->value();
  char result[100];
  strcpy(result,dir);
  strcat(result,"/");
  strcat(result,file);
  open_folder(result, b1, i1);
}

void b2_clicked() {
  b1->deselect();
  if( Fl::event_button() == FL_RIGHT_MOUSE )
      return;
  int index = b2->value();
  if (index == 0) return;
  const char *file = b2->text(index);
  const char *dir = i2->value();
  char result[100];
  strcpy(result,dir);
  strcat(result,"/");
  strcat(result,file);
  open_folder(result, b2, i2);
}

void i1_changed() {
  const char *result = i1->value();
  open_folder(result, b1, i1);
}

void i2_changed() {
  const char *result = i2->value();
  open_folder(result, b2, i2);
}

void action_view() {
  printf("action_view");
}

void action_edit() {
  const char *file;
    const char *dir;
    
      for (int n=1; n<=b1->size(); n++) {
        if ( b1->selected(n) ) {
            file = b1->text(n);
            dir = i1->value();
            char result[100];
            strcpy(result,dir);
            strcat(result,"/");
            strcat(result,file);
            std::string s = "geany ";
            s=s+result+" &";
            system(s.c_str());} {}
        }
  
      for (int n=1; n<=b2->size(); n++) {
        if ( b2->selected(n) ) {
            file = b2->text(n);
            dir = i2->value();
            char result[100];
            strcpy(result,dir);
            strcat(result,"/");
            strcat(result,file);
            std::string s = "geany ";
            s=s+result+" &";
            system(s.c_str());} {}
        }
}

void action_exit() {
  exit(0);
}

void action_copy() {
  printf("action_copy");
}

void action_move() {
  printf("action_move");
}

Fl_Double_Window *win_nf=(Fl_Double_Window *)0;

Fl_Input *win_nf_input=(Fl_Input *)0;

static void cb_Cancel(Fl_Button*, void*) {
  win_nf->hide();
}

static void cb_OK(Fl_Button*, void*) {
  const char *dir = i2->value();
const char *file = win_nf_input->value();
char result[100];
strcpy(result,dir);
strcat(result,"/");
strcat(result,file);
mkdir(result, 0755);
open_folder(dir, b2, i2);
win_nf->hide();
}

Fl_Double_Window* action_new_folder() {
  { win_nf = new Fl_Double_Window(455, 95, "FLTK Commander");
    { new Fl_Box(5, 4, 95, 29, "New directory:");
    } // Fl_Box* o
    { win_nf_input = new Fl_Input(5, 36, 445, 24);
    } // Fl_Input* win_nf_input
    { Fl_Button* o = new Fl_Button(345, 65, 105, 25, "Cancel");
      o->color(FL_LIGHT2);
      o->callback((Fl_Callback*)cb_Cancel);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(235, 65, 105, 25, "OK");
      o->color(FL_LIGHT2);
      o->callback((Fl_Callback*)cb_OK);
    } // Fl_Button* o
    win_nf->set_modal();
    win_nf->end();
  } // Fl_Double_Window* win_nf
  win_nf->show();
  return win_nf;
}

void action_delete() {
  const char *file;
  const char *dir;
    
      for (int n=1; n<=b1->size(); n++) {
        if ( b1->selected(n) ) {
            file = b1->text(n);
            dir = i1->value();
            char result[100];
            strcpy(result,dir);
            strcat(result,"/");
            strcat(result,file);
            int ret_code = std::remove(result);
            open_folder(dir, b1, i1);} {}
        }
  
      for (int n=1; n<=b2->size(); n++) {
        if ( b2->selected(n) ) {
            file = b2->text(n);
            dir = i2->value();
            char result[100];
            strcpy(result,dir);
            strcat(result,"/");
            strcat(result,file);
            int ret_code = std::remove(result);
            open_folder(dir, b2, i2);} {}
        }
}
