// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "test.h"

Fl_Double_Window *w=(Fl_Double_Window *)0;

int main(int argc, char **argv) {
  { w = new Fl_Double_Window(200, 200);
    w->end();
  } // Fl_Double_Window* w
  w->show(argc, argv);
  return Fl::run();
}
