// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef test_h
#define test_h
#include <FL/Fl.H>
void action_poweroff(Fl_Widget*, void*);
void action_logout(Fl_Widget*, void*);
void action_suspend(Fl_Widget*, void*);
void action_reboot(Fl_Widget*, void*);
void action_quit(Fl_Widget*, void*);
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *main_window;
#include <FL/Fl_Button.H>
#include <FL/Fl_Group.H>
extern Fl_Button *button_cancel;
#endif
