// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef test_h
#define test_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *about_window;
#include <FL/Fl_Box.H>
Fl_Double_Window* action_about(Fl_Widget*, void*);
void action_quit(Fl_Widget*, void*);
void button_cb(Fl_Widget*, const char* command);
extern Fl_Double_Window *main_window;
#include <FL/Fl_Button.H>
#include <FL/Fl_Menu_Bar.H>
extern Fl_Menu_Item menu_[];
#endif
