// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "test.h"

Fl_Double_Window *about_window=(Fl_Double_Window *)0;

Fl_Double_Window* action_about(Fl_Widget*, void*) {
  { about_window = new Fl_Double_Window(335, 255, "About Dialog");
    { Fl_Box* o = new Fl_Box(15, 43, 310, 62, "FLTK Demo");
      o->labelsize(45);
      o->labelcolor((Fl_Color)64);
    } // Fl_Box* o
    { Fl_Box* o = new Fl_Box(55, 163, 230, 57, "Author: Anonymous");
      o->labelcolor((Fl_Color)64);
    } // Fl_Box* o
    about_window->set_modal();
    about_window->end();
  } // Fl_Double_Window* about_window
  about_window->show();
  return about_window;
}

void action_quit(Fl_Widget*, void*) {
  exit(0);
}

void button_cb(Fl_Widget*, const char* command) {
  system(command);
}

Fl_Double_Window *main_window=(Fl_Double_Window *)0;

static void cb_Task(Fl_Button* o, void*) {
  button_cb(o, "lxtask&");
}

static void cb_Appearance(Fl_Button* o, void*) {
  button_cb(o, "lxappearance&");
}

Fl_Menu_Item menu_[] = {
 {"File", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 16, 0},
 {"New", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 15, 32},
 {"Open", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 15, 32},
 {"Save", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 15, 32},
 {"Exit", 0,  (Fl_Callback*)action_quit, 0, 0, FL_NORMAL_LABEL, 0, 15, 32},
 {0,0,0,0,0,0,0,0,0},
 {"Help", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 16, 0},
 {"About", 0,  (Fl_Callback*)action_about, 0, 0, FL_NORMAL_LABEL, 0, 15, 32},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

int main(int argc, char **argv) {
  { main_window = new Fl_Double_Window(640, 460, "FLTK Test");
    { Fl_Button* o = new Fl_Button(15, 50, 300, 50, "Task");
      o->color((Fl_Color)92);
      o->selection_color((Fl_Color)9);
      o->labelfont(8);
      o->labelsize(30);
      o->callback((Fl_Callback*)cb_Task);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(325, 50, 300, 50, "Appearance");
      o->color((Fl_Color)92);
      o->selection_color((Fl_Color)9);
      o->labelfont(8);
      o->labelsize(30);
      o->callback((Fl_Callback*)cb_Appearance);
    } // Fl_Button* o
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 10, 640, 30);
      o->color((Fl_Color)48);
      o->selection_color((Fl_Color)112);
      o->labelfont(4);
      o->labelcolor(FL_GRAY0);
      o->textfont(4);
      o->menu(menu_);
    } // Fl_Menu_Bar* o
    main_window->size_range(410, 90);
    main_window->end();
    main_window->resizable(main_window);
  } // Fl_Double_Window* main_window
  main_window->show(argc, argv);
  return Fl::run();
}
