// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "test.h"

Fl_Double_Window *mainwin=(Fl_Double_Window *)0;

Fl_File_Browser *browser1=(Fl_File_Browser *)0;

Fl_File_Browser *browser2=(Fl_File_Browser *)0;

Fl_Input *input1=(Fl_Input *)0;

Fl_Input *input2=(Fl_Input *)0;

Fl_Button *button_view=(Fl_Button *)0;

Fl_Button *button_edit=(Fl_Button *)0;

Fl_Button *button_copy=(Fl_Button *)0;

Fl_Button *button_move=(Fl_Button *)0;

Fl_Button *button_new_folder=(Fl_Button *)0;

Fl_Button *button_delete=(Fl_Button *)0;

Fl_Button *button_exit=(Fl_Button *)0;

Fl_Menu_Item menu_[] = {
 {"File", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Exit", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

int main(int argc, char **argv) {
  { mainwin = new Fl_Double_Window(775, 610, "FLTK Commander");
    mainwin->color(FL_LIGHT1);
    { browser1 = new Fl_File_Browser(5, 70, 380, 505);
      browser1->selection_color(FL_DARK_RED);
      browser1->labelfont(5);
      browser1->labelsize(20);
      browser1->labelcolor(FL_GRAY0);
      browser1->textfont(5);
      browser1->textsize(15);
      browser1->type(FL_MULTI_BROWSER);
    } // Fl_File_Browser* browser1
    { browser2 = new Fl_File_Browser(390, 70, 380, 505);
      browser2->selection_color(FL_DARK_RED);
      browser2->labelfont(5);
      browser2->labelsize(20);
      browser2->labelcolor(FL_GRAY0);
      browser2->textfont(5);
      browser2->textsize(15);
      browser2->type(FL_MULTI_BROWSER);
    } // Fl_File_Browser* browser2
    { input1 = new Fl_Input(5, 39, 380, 25);
      input1->selection_color((Fl_Color)219);
      input1->labelcolor(FL_GRAY0);
      input1->textfont(5);
      input1->textsize(15);
      input1->when(FL_WHEN_ENTER_KEY);
    } // Fl_Input* input1
    { input2 = new Fl_Input(390, 40, 380, 25);
      input2->selection_color((Fl_Color)219);
      input2->labelcolor(FL_GRAY0);
      input2->textfont(5);
      input2->textsize(15);
      input2->when(FL_WHEN_ENTER_KEY);
    } // Fl_Input* input2
    { Fl_Group* o = new Fl_Group(5, 575, 790, 35);
      { button_view = new Fl_Button(5, 580, 105, 25, "F3 View");
        button_view->shortcut(0xffc0);
        button_view->color(FL_LIGHT2);
      } // Fl_Button* button_view
      { button_edit = new Fl_Button(115, 580, 105, 25, "F4 Edit");
        button_edit->shortcut(0xffc1);
        button_edit->color(FL_LIGHT2);
      } // Fl_Button* button_edit
      { button_copy = new Fl_Button(225, 580, 105, 25, "F5 Copy");
        button_copy->shortcut(0xffc2);
        button_copy->color(FL_LIGHT2);
      } // Fl_Button* button_copy
      { button_move = new Fl_Button(335, 580, 105, 25, "F6 Move");
        button_move->shortcut(0xffc3);
        button_move->color(FL_LIGHT2);
      } // Fl_Button* button_move
      { button_new_folder = new Fl_Button(445, 580, 105, 25, "F7 New Folder");
        button_new_folder->shortcut(0xffc4);
        button_new_folder->color(FL_LIGHT2);
      } // Fl_Button* button_new_folder
      { button_delete = new Fl_Button(555, 580, 105, 25, "F8 Delete");
        button_delete->shortcut(0xffc5);
        button_delete->color(FL_LIGHT2);
      } // Fl_Button* button_delete
      { button_exit = new Fl_Button(665, 580, 105, 25, "Alt+F4 Exit");
        button_exit->shortcut(0xffe9);
        button_exit->color(FL_LIGHT2);
      } // Fl_Button* button_exit
      o->end();
    } // Fl_Group* o
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(5, 7, 765, 25);
      o->box(FL_FLAT_BOX);
      o->color(FL_LIGHT1);
      o->menu(menu_);
    } // Fl_Menu_Bar* o
    mainwin->size_range(700, 410);
    mainwin->end();
    mainwin->resizable(mainwin);
  } // Fl_Double_Window* mainwin
  mainwin->show(argc, argv);
  return Fl::run();
}
