// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef test_h
#define test_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *mainwin;
#include <FL/Fl_File_Browser.H>
extern Fl_File_Browser *browser1;
extern Fl_File_Browser *browser2;
#include <FL/Fl_Input.H>
extern Fl_Input *input1;
extern Fl_Input *input2;
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
extern Fl_Button *button_view;
extern Fl_Button *button_edit;
extern Fl_Button *button_copy;
extern Fl_Button *button_move;
extern Fl_Button *button_new_folder;
extern Fl_Button *button_delete;
extern Fl_Button *button_exit;
#include <FL/Fl_Menu_Bar.H>
extern Fl_Menu_Item menu_[];
#define menuitem_exit (menu_+1)
#endif
