// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef test_h
#define test_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win;
#include <FL/Fl_File_Browser.H>
extern void b1_clicked(Fl_File_Browser*, void*);
extern Fl_File_Browser *b1;
extern void b2_clicked(Fl_File_Browser*, void*);
extern Fl_File_Browser *b2;
#include <FL/Fl_Input.H>
extern void i1_changed(Fl_Input*, void*);
extern Fl_Input *i1;
extern void i2_changed(Fl_Input*, void*);
extern Fl_Input *i2;
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
extern void action_view(Fl_Button*, void*);
extern void action_edit(Fl_Button*, void*);
extern void action_copy(Fl_Button*, void*);
extern void action_move(Fl_Button*, void*);
extern void action_new_folder(Fl_Button*, void*);
extern void action_delete(Fl_Button*, void*);
extern void action_exit(Fl_Button*, void*);
#include <FL/Fl_Menu_Bar.H>
extern void action_exit(Fl_Menu_*, void*);
extern Fl_Menu_Item menu_[];
#endif
