// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "test.h"

Fl_Double_Window *win=(Fl_Double_Window *)0;

Fl_File_Browser *b1=(Fl_File_Browser *)0;

Fl_File_Browser *b2=(Fl_File_Browser *)0;

Fl_Input *i1=(Fl_Input *)0;

Fl_Input *i2=(Fl_Input *)0;

Fl_Menu_Item menu_[] = {
 {"File", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Exit", 0,  (Fl_Callback*)action_exit, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

int main(int argc, char **argv) {
  { win = new Fl_Double_Window(775, 610, "FLTK Commander");
    { b1 = new Fl_File_Browser(5, 70, 380, 505);
      b1->selection_color(FL_DARK_RED);
      b1->labelfont(5);
      b1->labelsize(20);
      b1->labelcolor(FL_GRAY0);
      b1->textfont(5);
      b1->textsize(15);
      b1->callback((Fl_Callback*)b1_clicked);
      b1->type(FL_MULTI_BROWSER);
    } // Fl_File_Browser* b1
    { b2 = new Fl_File_Browser(390, 70, 380, 505);
      b2->selection_color(FL_DARK_RED);
      b2->labelfont(5);
      b2->labelsize(20);
      b2->labelcolor(FL_GRAY0);
      b2->textfont(5);
      b2->textsize(15);
      b2->callback((Fl_Callback*)b2_clicked);
      b2->type(FL_MULTI_BROWSER);
    } // Fl_File_Browser* b2
    { i1 = new Fl_Input(5, 39, 380, 25);
      i1->selection_color((Fl_Color)219);
      i1->labelcolor(FL_GRAY0);
      i1->textfont(5);
      i1->textsize(15);
      i1->callback((Fl_Callback*)i1_changed);
      i1->when(FL_WHEN_ENTER_KEY);
    } // Fl_Input* i1
    { i2 = new Fl_Input(390, 40, 380, 25);
      i2->selection_color((Fl_Color)219);
      i2->labelcolor(FL_GRAY0);
      i2->textfont(5);
      i2->textsize(15);
      i2->callback((Fl_Callback*)i2_changed);
      i2->when(FL_WHEN_ENTER_KEY);
    } // Fl_Input* i2
    { Fl_Group* o = new Fl_Group(5, 575, 790, 35);
      { Fl_Button* o = new Fl_Button(5, 580, 105, 25, "F3 View");
        o->shortcut(0xffc0);
        o->color(FL_LIGHT2);
        o->callback((Fl_Callback*)action_view);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(115, 580, 105, 25, "F4 Edit");
        o->shortcut(0xffc1);
        o->color(FL_LIGHT2);
        o->callback((Fl_Callback*)action_edit);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(225, 580, 105, 25, "F5 Copy");
        o->shortcut(0xffc2);
        o->color(FL_LIGHT2);
        o->callback((Fl_Callback*)action_copy);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(335, 580, 105, 25, "F6 Move");
        o->shortcut(0xffc3);
        o->color(FL_LIGHT2);
        o->callback((Fl_Callback*)action_move);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(445, 580, 105, 25, "F7 New Folder");
        o->shortcut(0xffc4);
        o->color(FL_LIGHT2);
        o->callback((Fl_Callback*)action_new_folder);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(555, 580, 105, 25, "F8 Delete");
        o->shortcut(0xffc5);
        o->color(FL_LIGHT2);
        o->callback((Fl_Callback*)action_delete);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(665, 580, 105, 25, "Alt+F4 Exit");
        o->color(FL_LIGHT2);
        o->callback((Fl_Callback*)action_exit);
      } // Fl_Button* o
      o->end();
    } // Fl_Group* o
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(5, 7, 765, 25);
      o->box(FL_FLAT_BOX);
      o->menu(menu_);
    } // Fl_Menu_Bar* o
    win->size_range(700, 410);
    win->end();
    win->resizable(win);
  } // Fl_Double_Window* win
  win->show(argc, argv);
  return Fl::run();
}
